repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  
    hooks:
      - id: black
        language_version: python3

  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: v2.7.4  # Choose a tag in the repo
  #   hooks:
  #     - id: pylint

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pipenv run python -m pytest test/test.py
        language: system
        types: [python]
        pass_filenames: false
