#!/bin/bash

# Run Black for formatting
echo "Running Black..."
black .
if [ $? -ne 0 ]; then
    echo "Black formatting failed. Please fix the issues before committing."
    exit 1
fi

# Run Pylint for linting
echo "Running Pylint..."
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')
if [ -z "$files" ]; then
    echo "No Python files to lint."
else
    for file in $files; do
        pylint "$file"
        if [ $? -ne 0 ]; then
            echo "Pylint check failed for $file. Please fix the issues before committing."
            exit 1
        fi
    done
fi

# Run unit tests
echo "Running unit tests..."
pytest
if [ $? -ne 0 ]; then
    echo "Unit tests failed. Please fix the issues before committing."
    exit 1
fi

echo "All checks passed. Proceeding with commit."
