apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygencs-deploy
  namespace: grp01eq7-namespace
  labels:
    app: oxygencs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxygencs
  template:
    metadata:
      labels:
        app: oxygencs
    spec:
      containers:
      - name: oxygencs
        image: tktbruv/oxygencs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"
        envFrom:
        - configMapRef:
            name: hvac-configmaps
        - secretRef:
            name: hvac-secrets