name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --ignore-pipfile

    - name: Run tests
      run: pipenv run pytest

    - name: Build Docker image
      run: docker build -t oxygencs-app .

    - name: Login to DockerHub
      run: echo "${{ secrets.log680team7 }}" | docker login -u "${{ secrets.tktbruv }}" --password-stdin

    - name: Push Docker image
      run: |
        docker tag oxygencs-app ${{ secrets.tktbruv }}/oxygencs-app:latest
        docker push ${{ secrets.tktbruv }}/oxygencs-app:latest
